# SPDX-License-Identifier: AGPL-3.0-only

"""Mixin contract protocol for the composed MediaApp.

``MediaAppProtocol`` documents every attribute and cross-mixin method
that the 10 mixin classes expect from ``self`` at runtime.  Type-hinting
each mixin method with ``self: MediaAppProtocol`` lets mypy catch
renames and interface drift at compile time.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Protocol

if TYPE_CHECKING:
    import threading
    from collections.abc import Callable
    from typing import Any, Literal

    from textual.containers import Container, Horizontal, Vertical
    from textual.dom import DOMNode
    from textual.geometry import Size
    from textual.screen import Screen
    from textual.timer import Timer
    from textual.widgets import Button, DataTable, ListView, Static

    from nyrx.models import MediaRequest
    from nyrx.modes import Source, View
    from nyrx.player import MPVIPC
    from nyrx.queues import PlaybackQueue
    from nyrx.sources import Source as SourceABC
    from nyrx.sources.radio_index import StationIndex
    from nyrx.widgets.artist_profile import ArtistProfileView
    from nyrx.widgets.base_now_playing import BaseNowPlaying
    from nyrx.widgets.download import DownloadWidget
    from nyrx.widgets.history_item import HistoryItem
    from nyrx.widgets.liked_screen import LikedScreen
    from nyrx.widgets.result_item import ResultItem
    from nyrx.widgets.sc_home import SCHomeView
    from nyrx.widgets.tv_home import TVHomeView
    from nyrx.widgets.tv_series import TVSeriesView
    from nyrx.widgets.watchlist_screen import WatchlistScreen


class MediaAppProtocol(Protocol):
    """Contract the composed ``MediaApp`` satisfies for all its mixins.

    Every attribute/method listed here is accessed via ``self`` from at
    least one mixin file.  Adding a new cross-mixin dependency means
    adding it here too; removing one means removing it from here.
    """

    # ── Textual App methods (accessed from mixins via self) ────────
    @property
    def screen(self) -> Screen: ...
    @property
    def focused(self) -> DOMNode | None: ...
    @property
    def log(self) -> Any: ...
    @property
    def screen_stack(self) -> list[Screen]: ...
    @property
    def size(self) -> Size: ...

    theme: Any

    def query_one(
        self, selector: str | type[Any], *args: Any, **kwargs: Any
    ) -> Any: ...
    def notify(self, message: str, *args: Any, **kwargs: Any) -> None: ...
    def set_interval(
        self, interval: float, callback: Any, *args: Any, **kwargs: Any
    ) -> Timer: ...
    def set_timer(
        self, delay: float, callback: Any, *args: Any, **kwargs: Any
    ) -> Timer: ...
    def push_screen(self, screen: Screen, *args: Any, **kwargs: Any) -> None: ...
    def pop_screen(self) -> None: ...
    def call_from_thread(self, callback: Any, *args: Any, **kwargs: Any) -> Any: ...
    def call_later(self, callback: Any, *args: Any, **kwargs: Any) -> Any: ...
    def call_after_refresh(self, callback: Any, *args: Any, **kwargs: Any) -> None: ...
    def refresh(self, *, repaint: bool = True, layout: bool = False) -> None: ...
    def register_theme(self, theme: Any, *args: Any, **kwargs: Any) -> None: ...
    def watch(self, *args: Any, **kwargs: Any) -> None: ...
    def set_focus(self, widget: Any, scroll_visible: bool = True) -> None: ...
    def exit(self) -> None: ...

    # ── Source / View / Mode ────────────────────────────────────────
    _source: Source | None
    _view: View
    _audio_only: bool
    _quality: str
    _sources: dict[str, SourceABC]

    # ── Connectivity ────────────────────────────────────────────────
    _online: bool
    _consecutive_failures: int
    _offline_since: float | None
    _show_back_online: bool
    _back_online_timer: Timer | None
    _last_failed_query: str | None
    _connectivity_timer: Timer | None

    # ── Playback state ──────────────────────────────────────────────
    _mpv_ipc: MPVIPC | None
    _np_side: BaseNowPlaying | None
    _poll_timer: Timer | None
    _notify_timer: Timer | None
    _np_widgets: dict[str, BaseNowPlaying]
    _now_playing_data: dict | None
    _playback_queue: PlaybackQueue
    _stopping: bool
    _play_spinner_timer: Timer | None
    _cancel_active: bool
    _cancel_target_idx: int
    _last_known_pos: float
    _last_playing_data: dict | None
    _last_playback_pos: float
    _stalled_count: int
    _stream_ready: bool
    _play_start_time: float
    _play_token: int
    _resolve_token: int
    _search_token: int
    _sc_resolving: bool
    _tv_probing: bool
    _subs_tmpdir: str | None
    _queue_frozen: bool
    _last_icy_title: str
    _syncing: bool

    # ── Search / Results ────────────────────────────────────────────
    _all_results: list[dict]
    _query: str
    _page: int
    _page_size: int
    _exhausted: bool
    _search_histories: dict[str, list[str]]

    # ── Chip / History spinner ──────────────────────────────────────
    _spinning_history_item: HistoryItem | None
    _spinning_chip: Button | None
    _chip_spinner_timer: Timer | None
    _chip_spinner_idx: int

    # ── Following spinner state ─────────────────────────────────────
    _loading_artists: dict[str, str]
    _fs_spinner_frame: int
    _fs_spinner_timer: Timer | None

    # ── Navigation state ────────────────────────────────────────────
    _in_following: bool
    _in_artist_profile: bool
    _in_liked: bool
    _in_watchlist: bool
    _in_tv_series: bool
    _pending_delete_tmdb: int | None
    _pending_unfollow_artist: str | None
    _unlike_buffer: dict[str, dict]
    _source_states: dict
    _last_quit_press: float | None
    _download_dir: str | None
    _trending_region: str

    # ── SoundCloud state ────────────────────────────────────────────
    _sc_liked: list[dict]
    _sc_followed: list[dict]
    _feed: list[dict]
    _feed_populated: bool
    _regen_in_progress: bool
    _station_in_progress: bool
    _sc_home_focus: (
        tuple[Literal["chip"], str | None] | tuple[Literal["recent"], int | None] | None
    )

    # ── TV/Movies state ─────────────────────────────────────────────
    _tv_trending: list[dict]
    _tv_popular: list[dict]
    _tv_recs: list[dict]
    _tv_home_focus: tuple[Literal["chip"], str | None, int] | None

    # ── Radio state ─────────────────────────────────────────────────
    _station_index: StationIndex | None
    _radio_filter_name: str
    _radio_filter_tags: list[str]
    _radio_filter_countries: list[str]
    _radio_row_positions: dict[str, int]
    _radio_row_stations: dict[str, dict]
    _radio_page: int
    _radio_display_count: int
    _radio_total_filtered: int
    _radio_gen: int
    _switch_gen: int
    _trending_in_progress: bool

    # ── Download state ──────────────────────────────────────────────
    _download_state: dict | None
    _download_pending: list[dict]
    _download_paused_for_offline: bool
    _download_running_flag: threading.Event
    _download_cancel_flag: threading.Event
    _current_dl_params: dict | None
    _clear_dl_timer: Timer | None
    _dl_spinner_timer: Timer | None
    _dl_cancel_watchdog: Timer | None
    _pending_dl_data: dict | None
    _failed_downloads: list[dict]

    # ── Settings ────────────────────────────────────────────────────
    _settings_lock: threading.Lock
    _tv_bookmarks: list[dict]

    # ── Runtime-only attrs (set outside __init__) ───────────────────
    _last_focused_on_app_blur: DOMNode | None
    _pixel_size: int

    # ── Size floor state ────────────────────────────────────────────
    _min_size_locked: bool
    _min_size_watchdog: Timer | None

    def _check_size_floor(self) -> None: ...
    def _push_lock(self) -> None: ...
    def _pop_lock(self) -> None: ...

    # ── Widget references ───────────────────────────────────────────
    _w_results_focus: Static | None
    _w_sidebar_focus: Static | None
    _w_sidebar_context: Static | None
    _w_sidebar_queue: Static | None
    _w_download: DownloadWidget | None
    _w_radio_list: DataTable | None
    _w_radio_filter_hint: Static | None
    _w_results_list: ListView | None
    _w_empty_state: Container | None
    _w_empty_offline_banner: Static | None
    _w_empty_hint: Static | None
    _w_sc_offline_banner: Static | None
    _w_tv_offline_banner: Static | None
    _w_main_content: Container | None
    _w_history_list: ListView | None
    _w_radio_area: Vertical | None
    _w_empty_heading: Static | None
    _w_sc_home: SCHomeView | None
    _w_following_area: Horizontal | None
    _w_fs_left_list: DataTable | None
    _w_fs_center_list: ListView | None
    _w_fs_center_header: Static | None
    _w_welcome_topright: Static | None
    _w_artist_profile: ArtistProfileView | None
    _w_liked_screen: LikedScreen | None
    _w_tv_home: TVHomeView | None
    _w_tv_series: TVSeriesView | None
    _w_watchlist_screen: WatchlistScreen | None

    # ── Cross-mixin methods: PlaybackActions ────────────────────────
    def _play(self, request: MediaRequest, from_queue: bool = False) -> None: ...
    def _play_next_queued(self) -> None: ...
    def _refresh_watchlist_statuses(self) -> None: ...
    def _play_raw(self, data: dict, start_pos: float | None = None) -> None: ...
    def _sync_np_widget(self) -> None: ...
    def _stop_playback(self) -> None: ...
    def _refresh_queue_modal(self) -> None: ...
    def _get_focused_track(self) -> dict | None: ...
    def _current_item(self) -> ResultItem | None: ...
    def _tick_play_spinner(self) -> None: ...
    def _start_playback(self, data: dict, request: MediaRequest) -> None: ...
    def _finish_playback(self, ipc: MPVIPC | None) -> None: ...
    def _sync_finish(self, ipc: MPVIPC | None) -> None: ...
    def _tv_movies_finish(
        self, ipc: MPVIPC | None, subs_tmpdir: str | None, token: int
    ) -> None: ...
    def _resolve_then_play(self, source: SourceABC, data: dict, token: int) -> None: ...
    def _on_sc_resolved(
        self,
        data: dict,
        ipc: MPVIPC | None,
        resolved: dict,
        rendered: tuple[list[float], list[list[str]]] | None,
        token: int,
    ) -> None: ...
    def _play_tv_movies(self, data: dict, start_pos: float | None = None) -> None: ...
    def _play_tv_worker(
        self, data: dict, start_pos: float | None, token: int
    ) -> None: ...
    def _play_tv_ready(
        self, data: dict, ipc: MPVIPC | None, subs_tmpdir: str | None, token: int
    ) -> None: ...
    def _play_tv_failed(
        self, error_msg: str, subs_tmpdir: str | None = None, token: int | None = None
    ) -> None: ...
    def _poll_mpv(self) -> None: ...
    def _cleanup_mpv(self) -> None: ...
    def _clear_stopping(self) -> None: ...
    def _get_quality_format(self) -> str | None: ...
    def _get_quality_height(self) -> int | None: ...
    def _update_sc_home_sidebar_class(self) -> None: ...
    def _update_queue_indicator(self) -> None: ...
    def _open_browser_worker(self, data: dict) -> None: ...
    def _on_thumb_result(self, result: dict | None) -> None: ...
    def _on_episode_range_result(self, result: dict | None) -> None: ...
    def action_download(self, data: dict | None = None) -> None: ...

    @property
    def _np_focused(self) -> bool: ...

    @property
    def _sc_np_focused(self) -> bool: ...

    @property
    def _is_playing(self) -> bool: ...

    # ── Cross-mixin methods: NavigationActions ──────────────────────
    def _sidebar_wanted(self) -> bool: ...
    def _apply_sidebar(self, is_wide: bool) -> None: ...
    def _apply_view(self) -> None: ...
    def _update_landing_chrome(self) -> None: ...
    def _update_sidebar_content(self) -> None: ...
    def _exit_landing_mode(self) -> None: ...
    def _enter_landing_mode(self) -> None: ...
    def _queue_trending_genre(self, slug: str) -> None: ...
    def _show_mode_overlay(self, key: Source) -> None: ...
    def _update_offline_ui(self) -> None: ...
    def _apply_secondary_widgets(self) -> None: ...
    def _set_focus_for_current_view(self) -> None: ...
    def _on_source_changed(self) -> None: ...
    def _on_filter_applied(self, result: dict | None) -> None: ...
    def _stop_trending(self) -> None: ...
    def _process_trending_results(self, results: list[dict], label: str) -> None: ...
    def _on_quality_selected(self, label: str | None) -> None: ...
    def _on_trending_region_selected(self, country_code: str | None) -> None: ...
    def _copy_url_worker(self, url: str) -> None: ...
    def _switch_source(self, key: Source, show_overlay: bool = True) -> None: ...
    def _switch_source_heavy(self, key: Source, saved: dict | None) -> None: ...
    def _finalize_switch_chrome(self) -> None: ...
    def _push_key_reference(self) -> None: ...
    def action_open_filter(self) -> None: ...
    def action_switch_source_1(self) -> None: ...
    def action_switch_source_2(self) -> None: ...
    def action_switch_source_3(self) -> None: ...
    def action_switch_source_4(self) -> None: ...

    # ── Cross-mixin methods: SearchActions ──────────────────────────
    def _run_history_search(self, item: HistoryItem) -> None: ...
    def _show_page(self) -> None: ...
    def _stop_chip_spinner(self) -> None: ...
    def _start_chip_spinner(self) -> None: ...
    def _rebuild_history_list(self) -> None: ...
    def _show_info(self, msg: str = "") -> None: ...
    def _show_loading(self) -> None: ...
    def _switch_results_to(self, state: str) -> None: ...
    def _perform_search(self, limit: int) -> None: ...
    def _on_initial_results(self) -> None: ...
    def _on_fetch_done(self, target_page: int) -> None: ...
    def _fetch_next_page(self) -> None: ...
    def _history_key(self) -> str: ...
    def _on_search_result(self, result: str | dict | None) -> None: ...
    def _notify_once(self, msg: str, timeout: int = 3, **kwargs: Any) -> None: ...
    def _stop_history_spinner(self) -> None: ...
    def _advance_chip_spinner(self) -> None: ...
    def _apply_history_gradient(self) -> None: ...
    def _check_connectivity(self) -> bool: ...

    # ── Cross-mixin methods: SoundCloudActions ──────────────────────
    def _hide_liked(self) -> None: ...
    def _hide_following(self) -> None: ...
    def _hide_artist_profile(self) -> None: ...
    def _show_artist_profile(self, artist_id: str) -> None: ...
    def _show_following(self) -> None: ...
    def _show_liked(self) -> None: ...
    def _set_feed_loading(self) -> None: ...
    def _regen_feed_worker(self) -> None: ...
    def _populate_center_feed(self) -> None: ...
    def _refresh_feed_liked_indicators(self) -> None: ...
    def _handle_following_nav(self, key: str) -> bool: ...
    def _on_regen_complete(self) -> None: ...
    def _on_regen_error(self, msg: str) -> None: ...
    def _on_station_result(self, results: list[dict] | None, title: str) -> None: ...
    def _on_sync_url(self, result: str | None) -> None: ...
    def _sync_liked_worker(self, profile_url: str) -> None: ...
    def _finish_sync(self, merged: list[dict], count: int) -> None: ...
    def _finish_sync_resolve_error(self, profile_url: str) -> None: ...
    def _purge_unlike_buffer(self) -> None: ...
    def _sync_sc_np_metadata(self) -> None: ...
    def _check_stale_caches(self) -> None: ...

    _sc_api_blocked: bool

    def _cache_worker(self) -> None: ...
    def _populate_following_panels(self) -> None: ...
    def set_pending_unfollow(self, artist_id: str) -> None: ...
    def clear_pending_unfollow(self) -> None: ...
    def _update_following_row_style(self, artist_id: str, is_pending: bool) -> None: ...
    def _station_worker(self, track_id: str, title: str) -> None: ...
    def _is_artist_fully_cached(self, artist_id: str) -> bool: ...
    def _start_following_spinner(self, artist_id: str, list_index: int) -> None: ...
    def _tick_following_spinner(self) -> None: ...
    def _stop_following_spinner(self, artist_id: str) -> None: ...
    def _refresh_fs_spinners(self) -> None: ...
    def action_browse_collections(self, collection_id: str = "") -> None: ...

    # ── Cross-mixin methods: RadioActions ───────────────────────────
    def _play_radio(self, station: dict) -> None: ...
    def _populate_radio_list(self) -> None: ...
    def _populate_radio_list_async(self, snapshot: tuple) -> None: ...
    def _on_radio_rows_ready(self, rows: list[dict], meta: dict) -> None: ...
    def _switch_radio_to(self, state: str) -> None: ...
    def _show_radio_loading(self) -> None: ...
    def _update_radio_playing_indicator(self) -> None: ...
    def _deferred_load_index(self) -> None: ...
    def _toggle_radio_like(self, station: dict) -> None: ...
    def _maybe_refresh_radio(self) -> None: ...
    def _do_refresh_radio(self) -> None: ...
    def _on_index_loaded(self, idx: StationIndex) -> None: ...
    def _refresh_radio_item(self, uuid: str) -> None: ...

    @property
    def _radio_is_active(self) -> bool: ...

    # ── Cross-mixin methods: app.py helpers ─────────────────────────
    @property
    def _cancel_targets(self) -> list[str]: ...

    def _enter_cancel_mode(self) -> None: ...
    def _exit_cancel_mode(self) -> None: ...
    def _cycle_cancel_target(self, direction: int) -> None: ...
    def _sync_cancel_highlights(self) -> None: ...
    def _confirm_cancel(self) -> None: ...
    def _skip_playback(self) -> None: ...
    def _cancel_download(self) -> None: ...
    def _active_np_widget(self) -> BaseNowPlaying | None: ...
    def _displayed_np_widget(self) -> BaseNowPlaying | None: ...

    _debug: bool
    _profile: bool

    def _init_logging(self) -> None: ...
    def _log_latency(self, label: str, t0: float) -> None: ...
    def _configure_perf_logging(self) -> None: ...
    def _preheat_tmdb_cache(self) -> None: ...
    def _warm_sc_client(self) -> None: ...
    def _on_sc_client_warmed(self) -> None: ...
    def _on_home_selected(self, result: object) -> None: ...
    def _check_hotswap(self, manual: bool = False) -> None: ...
    def _on_manifest_url_submitted(self, url: str | None) -> None: ...
    def _on_hotswap_toggled(self, enabled: bool | None) -> None: ...
    def _populate_tv_home(self) -> None: ...
    def _refresh_tv_home(self) -> None: ...
    def _toggle_tv_bookmark(self) -> None: ...
    def _do_delete_bookmark(self, tmdb_id: int) -> None: ...
    def _on_tmdb_key_result(self, key: str | None) -> None: ...
    def _enrich_tv_bookmark(self, tmdb_id: int) -> None: ...
    def _reload_bookmarks(self) -> None: ...
    def _show_watchlist(self) -> None: ...
    def _hide_watchlist(self) -> None: ...
    def _hide_tv_series(self, widget: TVSeriesView) -> None: ...
    def _on_season_jump_result(self, result: int | None) -> None: ...
    def action_view_tv_series(self, tmdb_id: int) -> None: ...
    def action_show_watchlist(self) -> None: ...
    def action_delete_bookmark(self) -> None: ...
    def action_unfollow_artist(self) -> None: ...
    def action_play(self) -> None: ...
    def _save_tv_home_focus(self) -> None: ...
    def _restore_tv_home_focus(self) -> None: ...

    _tv_nav_stack: list[Callable[[], None]]

    def _push_tv_nav(self, restore: Callable[[], None]) -> None: ...
    def _pop_tv_nav(self) -> None: ...

    # ── Cross-mixin methods: DownloadActions ────────────────────────
    @staticmethod
    def _fmt_eta(eta: int) -> str: ...

    @staticmethod
    def _fmt_speed(speed: float) -> str: ...

    def _start_download(
        self,
        audio_only: bool = False,
        quality: str | None = None,
        yt_id: str | None = None,
        title: str | None = None,
        format_str: str | None = None,
        url: str | None = None,
        *,
        _user_initiated: bool = False,
    ) -> None: ...
    def _check_download_queue(self) -> None: ...
    def _enqueue_download(
        self,
        yt_id: str,
        title: str,
        audio_only: bool = False,
        format_str: str | None = None,
        url: str | None = None,
        source: str = "youtube",
        quality: str | None = None,
        extra: dict | None = None,
        notify: bool = True,
    ) -> None: ...
    def _enqueue_episode_range(self, result: dict) -> None: ...
    def _update_dl_progress(
        self, pct: float, speed: float, eta: int, yt_id: str
    ) -> None: ...
    def _dl_processing(self, title: str, stage: str = "processing") -> None: ...
    def _show_dl_progress(self, title: str) -> None: ...
    def _tick_dl_spinner(self) -> None: ...
    def _force_cancel_download(self) -> None: ...
    def _do_download(
        self,
        yt_id: str,
        title: str,
        on_progress: Callable[..., Any],
        audio_only: bool = False,
        format_str: str | None = None,
        url: str | None = None,
        postprocessor_callback: Callable[..., Any] | None = None,
    ) -> None: ...
    def _start_tv_movies_download(
        self, quality: str, yt_id: str | None = None, title: str | None = None
    ) -> None: ...
    def _do_tv_movies_download(
        self,
        data: dict,
        quality_label: str,
        on_progress: Callable[..., Any],
        on_postprocessor: Callable[..., Any],
    ) -> None: ...
    def _build_tv_output_path(
        self,
        title: str,
        year: str | None = None,
        media_type: str = "movie",
        series_title: str | None = None,
        season: int | None = None,
        episode: int | None = None,
        output_dir: str = "~/Videos",
    ) -> str: ...
    def _mux_tv_download(
        self,
        primary_path: str,
        vtt_paths: list[tuple[str, str]],
        extra_audio_paths: list[tuple[str, str]],
    ) -> None: ...
    def _dl_cancelled(self) -> None: ...
    def _dl_error(self, msg: str) -> None: ...
    def _dl_finished(self, filename: str) -> None: ...
    def _dl_already_exists(self, filename: str) -> None: ...
    def _clear_dl_state(self) -> None: ...
    def _on_dir_selected(self, path: str | None) -> None: ...

    # ── Cross-mixin methods: FocusHandlers ──────────────────────────
    def _render_focus_indicators(self) -> None: ...
    def _save_sc_home_focus(self) -> None: ...
    def _restore_sc_home_focus(self) -> None: ...
    def _on_screen_focus_changed(
        self, old: DOMNode | None, new: DOMNode | None
    ) -> None: ...
    def _on_app_screen_changed(self) -> None: ...
    def key_tab(self) -> None: ...
    def _focus_main_panel(self) -> None: ...

    @property
    def _side_focused(self) -> bool: ...

    @property
    def _sidebar_state(self) -> tuple[BaseNowPlaying | DownloadWidget | None, bool]: ...

    # ── Cross-mixin methods: KeyHandlers ────────────────────────────
    def _update_mode_indicator(self) -> None: ...
    def _update_keybind_bar(self) -> None: ...
    def _detect_key_context(self) -> str: ...
    def _sidebar_keybind_text(self) -> str | None: ...

    # ── Cross-mixin methods: SidebarHandlers ────────────────────────
    def _update_sidebar_context(self) -> None: ...

    # ── Cross-mixin methods: ConnectivityHandlers ───────────────────
    def _handle_connectivity_result(self, now_online: bool) -> None: ...
    def _tick_connectivity(self) -> None: ...
    def _connectivity_worker(self) -> None: ...
    def _on_went_offline(self) -> None: ...
    def _on_came_back_online(self) -> None: ...
    def _clear_back_online(self) -> None: ...
    def _resume_after_reconnect(self) -> None: ...
