# SPDX-License-Identifier: AGPL-3.0-only

from .api import (
    ProfileResolveError,
    batch_resolve_via_client_id,
    fetch_artist_collections,
    fetch_artist_likes,
    fetch_artist_profile,
    fetch_artist_uploads,
    fetch_playlist_tracks,
    fetch_station_ids,
    fetch_trending_playlist,
    fetch_waveform,
    get_station_tracks,
    resolve_sc_user,
    search_soundcloud,
)
from .cache import CACHE_QUEUE, enqueue_artist_cache, process_artist_cache
from .db import (
    TTL_HOURS,
    _get_db,
    _row_to_followed,
    _row_to_liked,
    delete_artist_cache,
    get_cached_artist_collections,
    get_cached_artist_likes,
    get_cached_artist_profile,
    get_cached_artist_uploads,
    get_feed_age,
    init_sc_db,
    load_feed,
    load_sc_followed,
    load_sc_likes,
    needs_artist_refresh,
    save_artist_collections,
    save_artist_likes,
    save_artist_profile,
    save_artist_uploads,
    save_feed,
    save_sc_followed,
    save_sc_likes,
)
from .feed import generate_feed, get_listened_ids, get_watched_secs
from .following import (
    follow_sc,
    is_sc_followed,
    unfollow_sc,
)
from .likes import is_sc_liked, sync_liked_from_profile, toggle_sc_like
from .source import SoundCloudSource

__all__ = [
    "CACHE_QUEUE",
    "ProfileResolveError",
    "TTL_HOURS",
    "_get_db",
    "_row_to_followed",
    "_row_to_liked",
    "batch_resolve_via_client_id",
    "delete_artist_cache",
    "enqueue_artist_cache",
    "fetch_artist_collections",
    "fetch_artist_likes",
    "fetch_artist_profile",
    "fetch_artist_uploads",
    "fetch_playlist_tracks",
    "fetch_station_ids",
    "fetch_trending_playlist",
    "fetch_waveform",
    "follow_sc",
    "generate_feed",
    "get_cached_artist_collections",
    "get_cached_artist_likes",
    "get_cached_artist_profile",
    "get_cached_artist_uploads",
    "get_feed_age",
    "get_listened_ids",
    "get_station_tracks",
    "get_watched_secs",
    "init_sc_db",
    "is_sc_followed",
    "is_sc_liked",
    "load_feed",
    "load_sc_followed",
    "load_sc_likes",
    "needs_artist_refresh",
    "process_artist_cache",
    "resolve_sc_user",
    "save_artist_collections",
    "save_artist_likes",
    "save_artist_profile",
    "save_artist_uploads",
    "save_feed",
    "save_sc_followed",
    "save_sc_likes",
    "SoundCloudSource",
    "search_soundcloud",
    "sync_liked_from_profile",
    "toggle_sc_like",
    "unfollow_sc",
]
